name: "Action: Build Image"

on:
  workflow_call:
    inputs:
      channel:
        required: false
        default: 'nightly'
        type: string
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        include:
          - image: "homelab-api"
            target: app_php_dev
            context: "./api"
          - image: "homelab-caddy"
            target: app_caddy
            context: "./api"
          - image: "homelab-pwa"
            target: dev
            context: "./pwa"
    
    steps:
      - uses: kilip/homelab-monitor/.github/workflows/image-build@dev
        with:
          image: ${{ matrix.image }}
          target: ${{ matrix.target }}
          context: ${{ matrix.context }}
          channel: ${{ inputs.channel }}
          version: ${{ inputs.version }}
          pushImages: 'true'
          updateMetadata: 'true'
