---
name: "Action: Testing CI"

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

jobs:
  build-images:
    uses: kilip/homelab-monitor/.github/workflows/build-images.yml@dev
    with:
      channel: "nightly"
      version: "testingz"
    secrets: inherit
