---
name: "Action: Testing CI"

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

jobs:
  build-api:
    uses: kilip/homelab-monitor/.github/workflows/image-build.yml@dev
    with:
      image: "homelab-api"
      target: app_php_dev
      context: "./api"
      pushImages: "true"
      channel: "nightly"
      updateMetadata: "true"
    secrets: inherit

