---
name: "Action: Image Build"

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup GHCR
        if: ${{ inputs.pushImages == 'true' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build api image for testing
        uses: docker/build-push-action@v4
        with:
          build-args: ./api
            VERSION=testing
            CHANNEL=testing
          context: ./api
          platforms: linux/amd64 # load does not support muti-arch https://github.com/docker/buildx/issues/290
          target: app_php_dev
          load: true
          tags: ghcr.io/${{ github.repository_owner }}/homelab-api:testing
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build caddy image for testing
        uses: docker/build-push-action@v4
        with:
          build-args: ./api
            VERSION=dev
            CHANNEL=dev
          context: ./api
          platforms: linux/amd64 # load does not support muti-arch https://github.com/docker/buildx/issues/290
          target: app_caddy
          load: true
          tags: ghcr.io/${{ github.repository_owner }}/homelab-caddy:testing
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build pwa image for testing
        uses: docker/build-push-action@v4
        with:
          build-args: ./pwa
            VERSION=dev
            CHANNEL=dev
          context: ./pwa
          platforms: linux/amd64 # load does not support muti-arch https://github.com/docker/buildx/issues/290
          load: true
          tags: ghcr.io/${{ github.repository_owner }}/homelab-pwa:testing
          cache-from: type=gha
          cache-to: type=gha,mode=max
