name: "Action: Build Image"

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      target:
        required: true
        type: string
      context:
        required: true
        type: string
      pushImages:
        required: false
        default: 'false'
        type: string
      channel:
        required: true
        default: 'stable'
        type: string
      version:
        required: false
        default: 'testingz'
        type: string
      updateMetadata:
        required: false
        default: 'true'
        type: string

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup workflow Variables
        id: vars
        shell: bash
        run: |-
          echo "chan_build_date=$(date --rfc-3339=seconds --utc)" >> $GITHUB_OUTPUT
          echo "chan_label_type=org.opencontainers.image" >> $GITHUB_OUTPUT

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
  
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Setup GHCR
        if: ${{ inputs.pushImages == 'true' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build all platforms
        id: release
        uses: docker/build-push-action@v4
        with:
          build-args: |-
            VERSION=${{ inputs.version }}
            CHANNEL=${{ inputs.channel }}
          labels: |-
            ${{ steps.vars.outputs.chan_label_type }}.created="${{ steps.vars.outputs.chan_build_date }}"
            ${{ steps.vars.outputs.chan_label_type }}.title="${{ inputs.image }} (${{ inputs.channel }})"
            ${{ steps.vars.outputs.chan_label_type }}.version="${{ inputs.version }}"
            ${{ steps.vars.outputs.chan_label_type }}.authors="Anthonius Munthi <me@itstoni.com>"
            ${{ steps.vars.outputs.chan_label_type }}.url="https://github.com/kilip/homelab-monitor"
            ${{ steps.vars.outputs.chan_label_type }}.build.url="https://github.com/kilip/homelab-monitor/actions/runs/${{ github.run_id }}"
            ${{ steps.vars.outputs.chan_label_type }}.documentation="https://github.com/kilip/homelab-monitor/README.md"
            ${{ steps.vars.outputs.chan_label_type }}.revision="${{ github.sha }}"
          context: ${{ inputs.context }}
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          push: ${{ inputs.pushImages == 'true' }}
          target: ${{ inputs.target }}
          tags: |-
            ghcr.io/${{ github.repository_owner }}/homelab-${{ inputs.image }}:${{ inputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
